version: '2'
services:
    quiz-app:
        image: quiz
        external_links:
            - quiz-mysql:mysql
            - quiz-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/quiz?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    quiz-mysql:
        extends:
            file: mysql.yml
            service: quiz-mysql
    quiz-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: quiz-elasticsearch
